### ISSUE TITLE
Anyone can upload images using mobile apps?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/lutim_ynh#17]
Hello,
I have just installed a private instance of Lutim.
When trying to use Lutim with its mobiel app http://www.gobl.im/, it allowed me to upload an image to my server without having to provide any login/password. The picture was available online and I could not find it in the "my images" page of any of my accounts.
Is this the standard behavior or is it a bug?

Thanks

**Comment by maniackcrudelis** [comment]
Nice app ! I didn't know it

So, of course no, it's not the expected behavior.
But, after install this app on my phone, I see I have nothing in my nginx log. But if you take a look at the lutim log (/var/log/lutim/production.log), you can see an entry like this:
```
[CREATION] 192.168.1.52 remote port:53280 pushed DSC_0104.JPG (path: files/nQyqaZSi.JPG)
```
Of course, this port is closed on my server.
On a second test, it uses the port 53383 throught my router (I use 4G for this test).

I think it doesn't open a port on the server, but on the phone. But even like that, how can they communicate first... ?

**Comment by maniackcrudelis** [comment]
OK, found...
A stupid error....

You can't access to /lutim/ but you can access to /lutim...

**Comment by maniackcrudelis** [comment]
OK, I gonna fix that. But, that will break this wonderful app if your app is not public...

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/YunoHost-Apps/lutim_ynh/commit/c238e68ba9c7996cbbf50ba422d4d3b5be7ae3b4

**Comment by ldidry** [comment]
@scith The "my images" page works only on the browser you uploaded the images with (it uses localStorage) => standard behavior of Lutim. (Goblim keeps informations about the uploaded images, allowing you to delete/reshare them)
For the "I can upload with Goblim even if my lutim is suppposed to be protected", @maniackcrudelis dealed with it.

**Comment by scith** [comment]
@ldidry Thanks, I see. We are thinking with @maniackcrudelis about a way to circumvent this problem, which is common to all apps protected behind SSO and having mobile applications. To be continued here: https://dev.yunohost.org/issues/905 :)

**Comment by ldidry** [comment]
Lutim will have ldap authentification, when I'll have the time to backport that feature from lstu
